apps/congreso/urls.py
from django.urls import path
from . import views

app_name = 'taller'

urlpatterns = [
	path('', views.inicio, name='tallerInicio'),
	path('registro', views.registro, name='tallerRegistro'),
	path('programa', views.programa, name='tallerPrograma'),
	path('talleres', views.talleres, name='tallerTalleres'),
	path('success/<str:tipoExito>', views.exito, name='tallerExito'),
	path('warning/<int:i>-<int:t>/<int:bandera>', views.warning, name='tallerWarning'),
	path('inscripcion/<int:idTaller>', views.inscripcion, name='tallerInscripcion'),

	path('manage', views.administradorInicio, name="administradorInicio"),
	path('manage/participantes', views.ViewParticipantes.as_view(), name="administradorParticipantes"),
	path('manage/participantesMondragon', views.participantesMondragon, name="administradorParticipantesMondragon"),
	path('manage/programa', views.ViewPrograma.as_view(), name="administradorPrograma"),
	path('manage/talleres', views.ViewTalleres.as_view(), name="administradorTalleres"),
	path('manage/inscripciones', views.ViewInscripciones.as_view(), name="administradorInscripciones"),
]

proyecto1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.congreso.urls')),
]

templates/base/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" type="text/css" href="{% static 'css/estilos.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Didact+Gothic|Questrial|Playfair+Display" rel="stylesheet">

	{% block estilos %}{% endblock %}
	{% if title %}
	<title>Detrás de tu trastorno - {{ title }}</title>
	{% else %}
	<title>Detrás de tu trastorno</title>
	{% endif %}
</head>
<body>
	<nav>
		{% block nav %}
			{% include 'base/nav.html' %}
		{% endblock %}
	</nav>
	
	<div class="container">
		{% if messages %}
		{% for message in messages %}
			<div class="alert alert-{{ message.tags }}">
				{{ message }}
			</div>
		{% endfor %}
	{% endif %}
		{% block contenido %}
		{% endblock %}
	</div>


</body>
</html>

templates/base/indexAdmin.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/estilos-admin.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/formAdmin.css' %}">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link href="https://fonts.googleapis.com/css?family=Didact+Gothic|Questrial|Playfair+Display" rel="stylesheet">

	{% block estilos %}{% endblock %}
	{% if title %}
	<title>Detrás de tu trastorno - {{ title }}</title>
	{% else %}
	<title>Detrás de tu trastorno</title>
	{% endif %}
</head>
<body>
	<nav>
		{% block nav %}
			{% include 'base/navAdmin.html' %}
		{% endblock %}
	</nav>
	
	<div class="container">
		{% block contenido %}
		{% endblock %}
	</div>

<script type="text/javascript" src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bootstrap/bootstrap.js' %}"></script>

</body>
</html>

templates/base/nav.html
<div class="enlaces">
	<a href="{% url 'taller:tallerTalleres' %}">Talleres</a>
	<a href="{% url 'taller:tallerPrograma' %}">Programa</a>
	<a href="{% url 'taller:tallerRegistro'%}">Registro</a>
	<a href="{% url 'taller:tallerInicio' %}">Inicio</a>
</div>

templates/base/navAdmin.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarToggler">
    <ul class="nav navbar-nav mr-auto mt-2 mt-lg-0">
       <li class="nav-item">
        <a class="nav-link" href="{% url 'taller:administradorInicio' %}">Menú</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'taller:administradorParticipantes' %}">Participantes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'taller:administradorParticipantesMondragon' %}">Mondragon</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'taller:administradorPrograma' %}">Programa</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'taller:administradorTalleres' %}">Talleres</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'taller:administradorInscripciones' %}">Inscripciones</a>
      </li>
    </ul>
  </div>
</nav>